### ISSUE TITLE
Incorrect crypto key statement in oauth authproxy example

### ISSUE THREAD

**Issue by sharon-tickell** [authp/authp.github.io#10]
In the Caddyfile example at https://github.com/authp/authp.github.io/blob/main/assets/conf/oauth/authproxy/Caddyfile, you have the line `crypto key sign-verify {env.JWT_SHARED_KEY}` in both the authentication portal block and the authorization portal block.

If I'm reading the docs at https://authp.github.io/docs/authenticate/auth-cookie correctly, shouldn't that be `sign-verify` as written in the authentication portal block, but just `verify` in the authorization policy?

**Comment by greenpau** [comment]
Updated docs. Pending release.
