### ISSUE TITLE
when trying to register a user via the portal it errors

### ISSUE THREAD

**Issue by discojc** [authp/authp.github.io#11]
I am trying to register a new user via the portal, and when I verify I get an error stating the file system is read only.
I have given full perms to the users.json, registrations.json along with the auth and local dirs however no luck.
In my config, its local auth, with the dir being /etc/caddy/auth/local (env.home did not work at all, didnt validate when i ran caddy adapt)

**Comment by greenpau** [comment]
@discojc , please re-open the issue in https://github.com/greenpau/caddy-security/issues/new?assignees=greenpau&labels=need+triage%2Cbreakfix&template=break-fix.md&title=breakfix%3A+CHANGE_ME
