### ISSUE TITLE
Cookie access_tocken being rejected after ~15min

### ISSUE THREAD

**Issue by Pan6ora** [authp/authp.github.io#25]
# Problem

After approximately 15 minutes the cookie creating by a successful login is rejected and you need to reconnect on next page reload.
This behavior is not related with `cookie lifetime` in Caddyfile.

After a reload, logs are showing messages on why it has been rejected.
  
![DeepinScreenshot_select-area_20220520152338](https://user-images.githubusercontent.com/45113213/169537311-99efb414-286c-41a6-bbd4-c7a7273705c0.png)

# What I've tried

- changing the setting `cookie samesite` to lax/strict/none (none of them fix this problem)
- checking cookie details: they seems correct

![DeepinScreenshot_select-area_20220520153200](https://user-images.githubusercontent.com/45113213/169538817-d4c7492f-2832-49f6-ac0e-ea87a1c6a46a.png)

# My caddyfile

```Caddyfile
{
	order authenticate before respond
	order authorize before basicauth
	security {
		ldap identity store main_ldap {
			realm "LDAP server"
			servers {
				ldaps://xxx ignore_cert_errors
			}
			attributes {
				name givenName
				surname sn
				username uid
				member_of gidNumber
				email mail
			}
			username "cn=xxx,dc=xxx"
			password "xxx"
			search_base_dn "ou=xxx,dc=xxx"
			search_filter "(uid=%s)"
			groups {
				"500" admin
			}
  		}
		authentication portal xxx_portal {
			enable identity store main_ldap
			cookie domain xxx.net
			crypto default token lifetime 86400
			cookie lifetime 86400
			cookie samesite lax
		}
		authorization policy xxx_admin {
			set auth url https://auth.xxx.net
			allow roles admin
		}
        }
}

auth.xxx.net {
	authenticate with xxx_portal
}
```

**Comment by greenpau** [comment]
@Pan6ora , please update to the latest version and retry your tests.

**Comment by Pan6ora** [comment]
I have just updated to the latest version (caddy 2.5.1, caddy-security 1.1.8). The problem is still the same.

**Comment by greenpau** [comment]
@Pan6ora , please update your config above. I want to see how is it configured.

Did you have a chance to review the following issue https://github.com/greenpau/caddy-security/issues/24#issuecomment-1019633596? it might be related to:

```
  crypto default token lifetime ...
  cookie lifetime ...
```

**Comment by Pan6ora** [comment]
I have updated the Caddyfile above. Adding `crypto default token lifetime` did not changed anything, the cookie is still rejected for the same reason.

About the config, caddy is run inside a docker container.

**Comment by greenpau** [comment]
@Pan6ora , what are the values for the below?

```
  crypto default token lifetime ...
  cookie lifetime ...
```

Have you tried removing `cookie samesite lax` from your config?

**Comment by greenpau** [comment]
Stale issue. Please re-open if necessary.
