### ISSUE TITLE
keycloak no id_token

### ISSUE THREAD

**Issue by omario36** [authp/authp.github.io#41]
Hello

Using the latest version of keycloak 20.x

my jwt token looks like :

`{
  "exp": 1670518964,
  "iat": 1670518904,
  "auth_time": 1670518904,
  "jti": "5ec29444-3409-4d6a-8999-c442a1942e0b",
  "iss": "https://#######/realms/master",
  "sub": "131d20a2-79d4-40ec-9e65-e4baaa488145",
  "typ": "Bearer",
  "azp": "test-caddy",
  "nonce": "N2giK5dZPbxpgivEMMvE50l0afvGUK00",
  "session_state": "e755a31c-12bd-4bb6-829a-9afe4cad4772",
  "scope": "profile email",
  "sid": "e755a31c-12bd-4bb6-829a-9afe4cad4772",
  "email_verified": true,
  "name": "Omar Omari",
  "groups": [
    "authp/admin",
    "default-roles-master",
    "authp/user",
    "authp/guest",
    "offline_access",
    "uma_authorization"
  ],
  "preferred_username": "oomari",
  "given_name": "Omar",
  "family_name": "Omari",
  "email": "########"
}`

I have this error 

`{"level":"debug","ts":1670518426.718966,"logger":"security","msg":"failed fetching OAuth 2.0 access token from the authorization server","session_id":"L4qZa6GSvpwfxej0lrPgQ0AshlmISYR20O2dm86l","request_id":"e0a6d25f-b162-4ce0-a175-483db6900fdb","error":"authorization server response has no \"id_token\" field"}`

**Comment by greenpau** [comment]
@omario36 , what is the config you are using?

**Comment by greenpau** [comment]
@omario36, try setting the following in your provider config.

```
  required_token_fields access_token
```

**Comment by omario36** [comment]
@greenpau any news please ? 
@axi92 can you please share with me your realm export and/or some screenshot, eventually where I have to add the mappers ... ? 
Thanks a lot

**Comment by axi92** [comment]
This is our config maybe it helps you.
I had the problem that I imported my realm config into keycloak and the keys are not in this export. So you have to regenerate all keys after the import and give the caddy the new key too.
```
{
	email admin@domain.link
	#debug

	order authenticate before respond
	order authorize before basicauth

	security {
		oauth identity provider keycloak {
			driver generic
			realm keycloak
			client_id {env.KEYCLOAK_CLIENT_ID}
			client_secret {env.KEYCLOAK_CLIENT_SECRET}
			scopes openid email profile
			#metadata_url https://keycloak.domain.com/auth/realms/master/.well-known/openid-configuration
			metadata_url https://keycloak.domain.com/realms/master/.well-known/openid-configuration
		}

		authentication portal myportal {
			crypto default token lifetime 3600
			crypto key sign-verify {env.JWT_SHARED_KEY}
			enable identity provider keycloak
			cookie domain domain.link
			ui {
				links {
					"alertmanager-03" https://alertmanager-03.domain.link icon "las la-link"
					"My Identity" "/whoami" icon "las la-user"
				}
			}
			transform user {
				match origin keycloak
				action add role authp/user
			}
			transform user {
				match origin local
				action add role authp/user
				ui link "Portal Settings" /settings icon "las la-cog"
			}
		}

		authorization policy mypolicy {
			set auth url https://auth.domain.link/
			allow roles authp/admin authp/user
			crypto key verify {env.JWT_SHARED_KEY}
		}
		authorization policy apipolicy {
			set token sources header query
			crypto key verify from directory /home/sfwadmin/sfw-proxy/jwt-public-keys/api
			crypto key token name api_token
			allow roles service
			acl default deny
			validate path acl
		}
		authorization policy monitoring {
			set auth url https://auth.domain.link/
			allow email user@domain.com
			crypto key verify {env.JWT_SHARED_KEY}
		}
	}
}
```

**Comment by axi92** [comment]
I dont think you have to do that, my only realm in my keycloak instance is called "mater" but in my caddy config its working with "realm keycloak". Maybe the caddy plugin does not treat the realm like a "keycloak realm". Instead the whole keycloak is the "realm"

**Comment by omario36** [comment]
I have these client scopes : 
![image](https://user-images.githubusercontent.com/10621369/207025085-cc8e5296-b71b-476b-9c4a-83133c92094e.png)
and in the email scope I added the groups mapper :
![image](https://user-images.githubusercontent.com/10621369/207025193-98a29e28-113b-41d2-b710-a89804294e6b.png)

Is it the same config you have ?

**Comment by axi92** [comment]
The scopes should not matter, as you give every user that comes from keycloak the authp/user
```
			transform user {
				match origin keycloak
				action add role authp/user
			}
```
And you allow in your policy:
`allow roles authp/admin authp/user`
Everybody can access from keycloak.

**Comment by axi92** [comment]
I don't know if this config is valid:
```
whoami.localhost:4443 {
  route {
		authenticate with myportal
  }	
  reverse_proxy whoami:80
  tls internal
}
```
You don't need to check the /whoami endpoint, authp denies access to that endpoint if you dont have a valid session. So no need to have that config IMHO.

**Comment by omario36** [comment]
@axi92 sorry but here whoami is the service that I want to secure buy keycloak oauth
To clarify the situation : I have a whoami docker service running on the same network with caddy 
so to expose it, I have to do something like that : `whoami.localhost:4443 {
   tls internal
   reverse_proxy whoami:80
   authenticate with myportal
}`

The new config is : 
```
{
  admin off
  debug
  http_port 880
  https_port 4443

	order authenticate before respond
	order authorize before basicauth

	security {
		oauth identity provider keycloak {
			driver generic
			realm keycloak
			client_id test-caddy
			client_secret 8KfOcqKQaSxczrM6Y0BqusTJofC4NkHO
			scopes openid email profile
			#required_token_fields access_token
			metadata_url https://auth.domain.tld/realms/master/.well-known/openid-configuration

		}

		authentication portal myportal {
			crypto default token lifetime 3600
			crypto key sign-verify "qwerty"
			enable identity provider keycloak
			cookie domain localhost
			ui {
				links {
					"whoami" https://whoami.localhost:4443/  icon "las la-star"
					"My Identity" "/whoami" icon "las la-user"
				}
			}
			transform user {
				match origin keycloak
				action add role authp/user
			}

			transform user {
				match origin local
				action add role authp/user
				ui link "Portal Settings" /settings icon "las la-cog"
			}
		}

		authorization policy mypolicy {
			set auth url https://auth.domain.tld/
			allow roles authp/admin authp/user
			crypto key verify "qwerty"
		}
		authorization policy monitoring {
			set auth url https://auth.domain.tld/
			allow email omar.omari@domain.tld
			crypto key verify "qwerty"
		}
	}
}

whoami.localhost:4443 {
   tls internal
   reverse_proxy whoami:80
   authenticate with myportal
}

log
```

Thanks for your support, I realy need to secure for example this whoami or another service proxied by the caddy.

**Comment by omario36** [comment]
maybe because the domain of my keycloak auth and the whoami service is different ? so AUTHP_SESSION_ID cookie is rejected ?

**Comment by omario36** [comment]
@axi92 Just a last question : how to secure for example proxied services ? 
@greenpau any link to update the documentation for using keycloak v20 + ?
