### ISSUE TITLE
Build fails with Docker and xcaddy

### ISSUE THREAD

**Issue by philipkukoba** [authp/authp.github.io#43]
I want to build a docker image with the caddy-security plugin, the build fails, here is the output:
![image](https://user-images.githubusercontent.com/99122730/211040265-ef0f3dab-48f4-4685-b6b7-a0e90acb9119.png)

My Dockerfile:

```
FROM caddy:2.6.2-builder AS builder
RUN xcaddy build \
    --with github.com/greenpau/caddy-security@v1.1.17
FROM caddy:2.6.2
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

It seems that some 'github.com/crewjam/saml@v0.4.10' package is causing the issue? Any ideas?

**Comment by greenpau** [comment]
@philipkukoba , please see for a temporary fix. https://github.com/greenpau/caddy-security/issues/196

This will not be necessary once upstream is fixed.

**Comment by philipkukoba** [comment]
> @philipkukoba , please see for a temporary fix. [greenpau/caddy-security#196](https://github.com/greenpau/caddy-security/issues/196)
> 
> This will not be necessary once upstream is fixed.

Please excuse me, should have checked open issues. Is there an ETA for the fix?
