### ISSUE TITLE
How does authp interact with the acme challenge URLs?

### ISSUE THREAD

**Issue by abgoyal** [authp/authp.github.io#44]
I just started using authp and it is absolutely terrific - easiest way to put a SSO authenticating proxy in front of other services that may not be so secure. 

I had one question: I use automatic certificates ("tls <email>" style). I understand that there are .well-known urls that LE will eventually want to ping when caddy tries to renew the certificate.

Would authp block these acme challenge requests? Or does caddy handle them before authp kicks in? 

I can't find any thing related to these in the Caddy or Authp docs.

**Comment by greenpau** [comment]
> Would authp block these acme challenge requests? Or does caddy handle them before authp kicks in?

@abgoyal , the latter. It is handled by caddy’s tls plugin which kicks in before authp (caddy-security plugin).

**Comment by abgoyal** [comment]
thanks @greenpau !
